Changing owner and permissions on /var/cache/icinga2
jjethwa/icinga2 pull request #293
Opened 2022-09-12 20:51 UTC by WingsLikeEagles

This should fix the issues when running on a Windows host.

2022-09-12 21:08 UTC, jjethwa requested changes

2022-09-12 21:08 UTC, jjethwa commented on Dockerfile
> +    && chown nagios:adm /var/cache/icinga2 \
Ownership looks to be nagios:nagios for /var/cache/icinga2

2022-09-12 21:08 UTC, jjethwa commented
Hey @WingsLikeEagles 

Thanks so much for the PR!  I've requested one small update.

2022-09-12 21:09 UTC, jjethwa commented
Reference: https://github.com/jjethwa/icinga2/issues/292

2022-10-13 00:31 UTC, WingsLikeEagles commented
Yeah, go for it.  I was just copying line 141 which had nagios:adm

2022-10-13 00:35 UTC, WingsLikeEagles commented
Ok, should be good.  Sorry for the delay.  I don't see notifications.

2022-10-13 07:06 UTC, merged

2022-10-13 07:07 UTC, jjethwa commented
Thanks, @WingsLikeEagles 

I'm on vacation right now, but will build and push the new image as soon as I get back. Thanks again 😃